
    $(function(){
      $("#fecha1").datepicker({
        changeMonth:true,
        changeYear:true,
      });
    })
    $(function(){
      $("#fecha2").datepicker({
        changeMonth:true,
        changeYear:true,
      });
    })
    $(function(){
      $("#fecha3").datepicker({
        changeMonth:true,
        changeYear:true,
      });
    })
    $(function(){
      $("#fecha4").datepicker({
        changeMonth:true,
        changeYear:true,
      });
    })
    $(function(){
      $("#fecha5").datepicker({
        changeMonth:true,
        changeYear:true,
      });
    })